import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RecoilContextProvider from '@/recoil-states/RecoilContextProvider'
import NavBar from './NavBar'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <RecoilContextProvider>
        <ClerkProvider afterSignUpUrl="/register">
          <body
            className={
              "relative bg-gradient-to-br from-teal-400  to-teal-900 min-h-screen"
            }
          >
            <NavBar></NavBar>
            <div className="mt-20"> {children}</div>
            <section className="bg-gray-800 text-white py-8 text-center mt-16">
              <h2 className="text-3xl font-bold">
                Monitor Pulse - Your Website's Guardian
              </h2>
              <p className="text-lg leading-6">
                Experience the peace of mind that comes with continuous website
                monitoring.
              </p>
            </section>
          </body>
        </ClerkProvider>
      </RecoilContextProvider>
    </html>
  );
}
